packages:
  - packages/a
  - packages/b
  - packages/c
  - packages/d
  - packages/e
  - packages/f
  - packages/g
  - packages/h
  - packages/i
  - packages/j
  - packages/k
  - packages/l
  - packages/m
  - packages/n
  - packages/o
  - packages/p
  - packages/q
  - packages/r
  - packages/s
  - packages/t
  - packages/u
  - packages/v
  - packages/w
  - packages/x
  - packages/y
  - packages/z
